In [11]:
from ucimlrepo import fetch_ucirepo 
  
# fetch dataset 
heart_disease = fetch_ucirepo(id=45) 
  
# data (as pandas dataframes) 
X = heart_disease.data.features 
y = heart_disease.data.targets 
  
# variable information 
display(X) 
display(y)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,63,1,1,145,233,1,2,150,0,2.3,3,0.0,6.0
1,67,1,4,160,286,0,2,108,1,1.5,2,3.0,3.0
2,67,1,4,120,229,0,2,129,1,2.6,2,2.0,7.0
3,37,1,3,130,250,0,0,187,0,3.5,3,0.0,3.0
4,41,0,2,130,204,0,2,172,0,1.4,1,0.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,45,1,1,110,264,0,0,132,0,1.2,2,0.0,7.0
299,68,1,4,144,193,1,0,141,0,3.4,2,2.0,7.0
300,57,1,4,130,131,0,0,115,1,1.2,2,1.0,7.0
301,57,0,2,130,236,0,2,174,0,0.0,2,1.0,3.0
302,38,1,3,138,175,0,0,173,0,0.0,1,NaN,3.0

     num
0      0
1      2
2      1
3      0
4      0
..   ...
298    1
299    2
300    3
301    1
302    0

[303 rows x 1 columns]

In [12]:
import pandas as pd

df = pd.concat([X, y], axis=1)

display(df)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,num
0,63,1,1,145,233,1,2,150,0,2.3,3,0.0,6.0,0
1,67,1,4,160,286,0,2,108,1,1.5,2,3.0,3.0,2
2,67,1,4,120,229,0,2,129,1,2.6,2,2.0,7.0,1
3,37,1,3,130,250,0,0,187,0,3.5,3,0.0,3.0,0
4,41,0,2,130,204,0,2,172,0,1.4,1,0.0,3.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,45,1,1,110,264,0,0,132,0,1.2,2,0.0,7.0,1
299,68,1,4,144,193,1,0,141,0,3.4,2,2.0,7.0,2
300,57,1,4,130,131,0,0,115,1,1.2,2,1.0,7.0,3
301,57,0,2,130,236,0,2,174,0,0.0,2,1.0,3.0,1
302,38,1,3,138,175,0,0,173,0,0.0,1,NaN,3.0,0

In [13]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Preenche os dados faltantes pela mediana da coluna
df = df.fillna(df.median(numeric_only=True))

# Transforma dos dados da coluna num em binário 0 para 0 e 1, 2, 3 e 4 para 1
df["num"] = df["num"].apply(lambda x: 1 if x > 0 else 0)

# Divisão dos dados entre treino e teste com proporção 80/20
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    stratify=y,
    random_state=42
)

# Escalonamento das colunas contínuas
colunas_cont = ["age", "trestbps", "chol", "thalach", "oldpeak"]
scaler = StandardScaler()
X_train[colunas_cont] = scaler.fit_transform(X_train[colunas_cont])
X_test[colunas_cont] = scaler.transform(X_test[colunas_cont])

display(X_train[colunas_cont].head())

          age  trestbps      chol   thalach   oldpeak
97   0.594945  1.020911  0.169014  0.307680  1.320132
82  -1.711319  0.463338  1.327117  1.411752 -0.900796
167 -0.063987  0.017280  0.720492  0.396006 -0.900796
288  0.155657 -0.094234 -0.511143  0.572657 -0.900796
71   1.363700 -0.373021  0.095483  0.572657 -0.729955